### ISSUE TITLE
特性请求：宽屏设备下首页居中显示

### ISSUE THREAD

**Issue by BoYanZh** [ASoulCnki/ASoulCnkiFrontend#22]
现在首页在宽屏设备下是左对齐的看起来比较奇怪

**Comment by ch3cknull** [comment]
> 现在首页在宽屏设备下是左对齐的看起来比较奇怪

可以问一下具体的设备类型吗，方便之后进行适配，以及出现问题的页面（枝网首页/枝江作文展）

问题确认的话应该在下个版本会进行适配

**Comment by BoYanZh** [comment]
枝网首页的`.container` 只有固定的 `640px`, `768px`, `1024px`, `1280px`, `1536px`这几个宽度，导致从不是这些宽度的屏幕浏览都会不居中。

**Comment by ch3cknull** [comment]
> 枝网首页的`.container` 只有固定的 `640px`, `768px`, `1024px`, `1280px`, `1536px`这几个宽度，导致从不是这些宽度的屏幕浏览都会不居中。

收到收到收到！我们会在之后的版本进行更改

<del>后续或许也会加个按钮做成类似纯净模式的功能（先挖个坑）<del>

**Comment by ch3cknull** [comment]
![image](https://user-images.githubusercontent.com/45302021/127187456-447e4cee-062b-4bf9-b690-2e33d8b761f5.png)


> 枝网首页的`.container` 只有固定的 `640px`, `768px`, `1024px`, `1280px`, `1536px`这几个宽度，导致从不是这些宽度的屏幕浏览都会不居中。

是类似于上图的样式吗，目前是对container做了居中处理

**Comment by BoYanZh** [comment]
![image](https://user-images.githubusercontent.com/32470225/127200216-01bfcb54-c495-4cfd-924b-788d4ee55e17.png)

宽度1920px

![image](https://user-images.githubusercontent.com/32470225/127200385-f9b88b6e-0139-4a11-8f33-2a32bb71273e.png)

宽度3840px 

Gecko和Chromium内核下都能复现

**Comment by ch3cknull** [comment]
收到收到收到！ 下个版本会修复捏

**Comment by ch3cknull** [comment]
> ![image](https://user-images.githubusercontent.com/32470225/127200216-01bfcb54-c495-4cfd-924b-788d4ee55e17.png)
> 
> 宽度1920px
> 
> ![image](https://user-images.githubusercontent.com/32470225/127200385-f9b88b6e-0139-4a11-8f33-2a32bb71273e.png)
> 
> 宽度3840px
> 
> Gecko和Chromium内核下都能复现

问题已经修复，可以看看新版本页面有无问题
https://asoulcnki.asia/
