### ISSUE TITLE
考虑出小程序版吗

### ISSUE THREAD

**Issue by Shimada666** [ASoulCnki/ASoulCnkiFrontend#41]
考虑出小程序版吗，现有网址查重需要好几次才能记住，如果增加小程序版可以增强用户的易用性，也方便用户分享。小程序自带的运营分析功能也比较 ok

**Comment by ch3cknull** [comment]
目前已有其他开发者在微信上线了类似小程序**枝网降重**
目前枝网降重内整合了查重和作文展的部分功能

所以短期内应该是不会出小程序的

**Comment by Shimada666** [comment]
> 目前已有其他开发者在微信上线了类似小程序**枝网降重**
> 目前枝网降重内整合了查重和作文展的部分功能
> 
> 所以短期内应该是不会出小程序的

好的捏
