### ISSUE TITLE
有没有考虑写一个浏览器插件呢

### ISSUE THREAD

**Issue by 1404860576** [ASoulCnki/ASoulCnkiFrontend#48]
通过调用后端api，在b站评论后面直接显示是否原创以及查重率。我目前写了一个简单的版本，效果如图。
![image](https://user-images.githubusercontent.com/35716043/130963926-47260f1c-7a98-4c69-bbd9-4212f2eda1a1.png)
线上的api有限流，我目前用的是本地的环境。如果需要的话，我把代码上传一下。

**Comment by ch3cknull** [comment]
之前 @sparanoid 做了一个手动查询的油猴脚本，地址
https://github.com/sparanoid/userscript

关于限流问题，目前的策略是 单IP 2r/s, 主要是为了防止恶意请求
普通au手动查询应该是可以满足的

再就是我们目前服务器性能问题（低配学生机）
插件用户基数上升后，可能存在大批量请求把服务器打死的情况？
